name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client
      - name: Run homework.sql
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -p 5432 -U postgres -d db_test -f homework.sql
      - name: CarTest
        id: cartest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: CarTest
          setup-command: ''
          command: PGPASSWORD=postgres psql -h 127.0.0.1 -p 5432 -U postgres -d db_test -f check-car.sql
            | grep -q 'The table contains only the specified rows.'
          timeout: 10
          max-score: 40
      - name: OwnerTest
        id: ownertest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: OwnerTest
          setup-command: ''
          command: PGPASSWORD=postgres psql -h 127.0.0.1 -p 5432 -U postgres -d db_test -f check-owner.sql
            | grep -q 'Owner entries exist.'
          timeout: 10
          max-score: 30
      - name: DollTest
        id: dolltest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: DollTest
          setup-command: ''
          command: PGPASSWORD=postgres psql -h 127.0.0.1 -p 5432 -U postgres -d db_test -f check-doll.sql
            | grep -q 'Doll entries exist.'
          timeout: 10
          max-score: 30
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CARTEST_RESULTS: "${{steps.cartest.outputs.result}}"
          OWNERTEST_RESULTS: "${{steps.ownertest.outputs.result}}"
          DOLLTEST_RESULTS: "${{steps.dolltest.outputs.result}}"
        with:
          runners: cartest,ownertest,dolltest
